# Generated by Django 4.1 on 2022-08-20 13:34

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=255)),
                ('categoryImage', models.ImageField(blank=True, null=True, upload_to='images/category/')),
            ],
        ),
        migrations.CreateModel(
            name='SearchKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchName', models.CharField(max_length=1000)),
                ('simDesc', models.TextField()),
                ('fullDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=0, max_length=16)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='images/usrProfile')),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('userTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('fullName', models.CharField(max_length=255)),
                ('aboutMe', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('contactMe', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usertypes')),
            ],
        ),
        migrations.CreateModel(
            name='QaCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('simDesc', models.TextField(blank=True, null=True)),
                ('fullDesc', ckeditor.fields.RichTextField()),
                ('regularPrice', models.FloatField(default=0)),
                ('saledPrice', models.FloatField(default=0)),
                ('itsFree', models.BooleanField(default=False)),
                ('dateRegistred', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('prevVideo', models.CharField(max_length=255000)),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to='images/courseImages/')),
                ('prevImage', models.ImageField(upload_to='images/courseImages/')),
                ('inrolledUsers', models.ManyToManyField(blank=True, null=True, related_name='inrolledU', to='api.userprofile')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
                ('searchKey', models.ManyToManyField(blank=True, null=True, to='api.searchkeys')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lessonNum', models.IntegerField(default=1, unique=True)),
                ('simDesc', models.TextField(blank=True, null=True)),
                ('fullDesc', ckeditor.fields.RichTextField()),
                ('lessonVideo', models.FileField(blank=True, null=True, upload_to='videos/lessons/')),
                ('lessonLink', models.TextField(blank=True, null=True)),
                ('dateRegistred', models.DateField(auto_now=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('theCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.qacourses')),
            ],
        ),
    ]
