# Generated by Django 4.1 on 2022-12-27 12:11

import api.models
import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponCode', models.CharField(default='', max_length=255)),
                ('expireDate', models.DateField(default=datetime.datetime(2022, 12, 29, 15, 11, 2, 794784))),
                ('discountPrice', models.FloatField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=255)),
                ('categoryDesc', models.TextField(default='')),
                ('categoryImage', models.ImageField(blank=True, null=True, upload_to='images/category/')),
                ('courses', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='InrolledCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referralCode', models.CharField(blank=True, max_length=255, null=True)),
                ('cupponCode', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('dateInrolled', models.DateTimeField(auto_now=True)),
                ('startDate', models.DateTimeField(auto_now=True)),
                ('endDate', models.DateField(default=api.models.one_month_from_today)),
                ('courseProgress', models.FloatField(default=0)),
                ('stayedSeconds', models.CharField(max_length=255)),
                ('itsLatestAccessedCourse', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='lessonCompo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compoName', models.CharField(default='', max_length=255)),
                ('orderNum', models.IntegerField(default=0)),
                ('lessonsCount', models.IntegerField(default=1)),
                ('totalHours', models.CharField(default='30:00', max_length=10)),
                ('simDesc', models.TextField(default='')),
            ],
            options={
                'ordering': ['orderNum'],
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lessonNum', models.IntegerField(default=1)),
                ('simDesc', models.TextField(blank=True, null=True)),
                ('fullDesc', ckeditor.fields.RichTextField()),
                ('lessonVideo', models.FileField(blank=True, null=True, upload_to='videos/lessons/')),
                ('lessonLink', models.CharField(blank=True, max_length=3000, null=True)),
                ('dateRegistred', models.DateField(auto_now=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('compo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theCompoLessons', to='api.lessoncompo')),
            ],
        ),
        migrations.CreateModel(
            name='SearchKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchName', models.CharField(max_length=1000)),
                ('simDesc', models.TextField()),
                ('fullDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magaca', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('qaabkaWaxbarashada', models.CharField(max_length=255)),
                ('maadadaAadDaneeneeso', models.CharField(max_length=255)),
                ('waqtiga', models.CharField(default='', max_length=255)),
                ('macalimiinta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=0, max_length=16)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='images/usrProfile')),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('userTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('fullName', models.CharField(max_length=255)),
                ('aboutMe', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('stayedSeconds', models.IntegerField(default=0)),
                ('facebook_link', models.CharField(blank=True, max_length=3000, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=3000, null=True)),
                ('third_link', models.CharField(blank=True, max_length=3000, null=True)),
                ('learnedSeconds', models.IntegerField(default=0)),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('contactMe', models.TextField(blank=True, null=True)),
                ('referralCode', models.CharField(default='qReff_9002', max_length=10)),
                ('teacherPoints', models.FloatField(default=1)),
                ('user_activated', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usertypes')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('text', models.TextField(default='')),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='api.userprofile')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theNotifications', to='api.userprofile')),
            ],
            options={
                'ordering': ['seen'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('dateRegistred', models.DateField(auto_now=True)),
                ('fullDesc', ckeditor.fields.RichTextField()),
                ('theLesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='QaCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(default='', max_length=2555)),
                ('simDesc', models.TextField(blank=True, null=True)),
                ('fullDesc', ckeditor.fields.RichTextField()),
                ('youLearn', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('regularPrice', models.FloatField(default=0)),
                ('showRegularPrice', models.BooleanField(default=True)),
                ('saledPrice', models.FloatField(default=0)),
                ('showDiscountPrice', models.BooleanField(default=True)),
                ('discountPrice', models.FloatField(default=0)),
                ('lessonCounts', models.IntegerField(default=0)),
                ('itsFree', models.BooleanField(default=False)),
                ('hasCertificate', models.BooleanField(default=False)),
                ('dateRegistred', models.DateField(auto_now=True)),
                ('level', models.CharField(default='Standared', max_length=255)),
                ('language', models.CharField(default='Somali', max_length=255)),
                ('houres', models.CharField(default='0', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('prevVideo', models.CharField(max_length=255000)),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to='images/courseImages/')),
                ('prevImage', models.ImageField(upload_to='images/courseImages/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coursecategory')),
                ('inrolledUsers', models.ManyToManyField(blank=True, null=True, related_name='inrolledU', to='api.userprofile')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='api.userprofile')),
                ('searchKeys', models.ManyToManyField(blank=True, null=True, to='api.searchkeys')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theInrolledCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inrolledcourse')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='theCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theLessons', to='api.qacourses'),
        ),
        migrations.CreateModel(
            name='LessonDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discText', models.TextField()),
                ('theAnswers', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('theLesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theDiscussions', to='api.lessons')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='lessoncompo',
            name='theCourse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theComponents', to='api.qacourses'),
        ),
        migrations.CreateModel(
            name='LessonAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansText', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('likedTheAnswer', models.ManyToManyField(blank=True, null=True, related_name='likedUsers', to='api.userprofile')),
                ('theDiscussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theDiscussionAnswers', to='api.lessondiscussion')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateName', models.CharField(max_length=255)),
                ('certificateDesc', models.CharField(max_length=2655)),
                ('certificateDate', models.DateField()),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theCertifications', to='api.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='inrolledcourse',
            name='currentLesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lessons'),
        ),
        migrations.AddField(
            model_name='inrolledcourse',
            name='theCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.qacourses'),
        ),
        migrations.AddField(
            model_name='inrolledcourse',
            name='theUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.CreateModel(
            name='FeedBacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=3)),
                ('date', models.DateField(auto_now=True)),
                ('fText', models.TextField()),
                ('isActive', models.BooleanField(default=False)),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theText', models.TextField(default='')),
                ('theRate', models.IntegerField(default=3)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('theCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theReviews', to='api.qacourses')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
