# Generated by Django 4.1 on 2022-08-20 16:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_qacourses_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacourses',
            name='youLearn',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
