# Generated by Django 4.1 on 2022-08-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_qacourses_youlearn'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacourses',
            name='houres',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='qacourses',
            name='level',
            field=models.CharField(default='Standared', max_length=255),
        ),
    ]
