# Generated by Django 4.1 on 2022-12-30 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_couponcode_expiredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='expireDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 1, 13, 59, 50, 644914)),
        ),
    ]
