# Generated by Django 4.1 on 2022-12-31 07:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_couponcode_expiredate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='contactMe',
            new_name='simAboutMe',
        ),
        migrations.AddField(
            model_name='inrolledcourse',
            name='paymentType',
            field=models.CharField(default='waafi', max_length=255),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='expireDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 10, 57, 16, 501961)),
        ),
        migrations.AlterField(
            model_name='qacourses',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructorCourse', to='api.userprofile'),
        ),
    ]
