# Generated by Django 4.1 on 2022-08-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='learnedSeconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stayedSeconds',
            field=models.IntegerField(default=0),
        ),
    ]
