# Generated by Django 4.1 on 2022-12-31 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_contactme_userprofile_simaboutme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='expireDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 10, 58, 8, 374226)),
        ),
    ]
