# Generated by Django 4.1 on 2022-08-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_learnedseconds_userprofile_stayedseconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='lessonCompo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compoName', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('text', models.TextField(default='')),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='api.userprofile')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
