# Generated by Django 4.1 on 2022-08-21 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_lessoncompo_usernotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='compo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.lessoncompo'),
        ),
    ]
