# Generated by Django 4.1 on 2022-12-31 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_couponcode_expiredate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contactMe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='expireDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 10, 59, 18, 525155)),
        ),
    ]
