# Generated by Django 4.1 on 2022-08-21 16:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_lessons_compo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('dateRegistred', models.DateField(auto_now=True)),
                ('fullDesc', ckeditor.fields.RichTextField()),
                ('theLesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lessons')),
            ],
        ),
    ]
