# Generated by Django 4.1 on 2022-12-31 08:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_contactme_alter_couponcode_expiredate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inrolledcourse',
            name='paymentType',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contactMe',
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='expireDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 11, 1, 42, 742255)),
        ),
        migrations.AlterField(
            model_name='qacourses',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='api.userprofile'),
        ),
    ]
