# Generated by Django 4.1 on 2022-08-22 18:19

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_coursecategory_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='InrolledCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('dateInrolled', models.DateTimeField(auto_now=True)),
                ('startDate', models.DateTimeField(auto_now=True)),
                ('endDate', models.DateField(default=api.models.one_month_from_today)),
                ('courseProgress', models.FloatField(default=0)),
                ('stayedSeconds', models.CharField(max_length=255)),
                ('currentLesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lessons')),
                ('theCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.qacourses')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
