# Generated by Django 4.1 on 2022-08-23 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_inrolledcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='inrolledcourse',
            name='itsLatestAccessedCourse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inrolledcourse',
            name='currentLesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lessons'),
        ),
    ]
