# Generated by Django 4.1 on 2023-01-05 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_inrolledcourse_paymenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inrolledcourse',
            name='paided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='expireDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 7, 10, 17, 16, 475178)),
        ),
    ]
