# Generated by Django 4.1 on 2022-08-23 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_inrolledcourse_itslatestaccessedcourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacourses',
            name='lessonCounts',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LessonDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discText', models.TextField()),
                ('theAnswers', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('theLesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lessons')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
