# Generated by Django 4.1 on 2022-08-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_qacourses_lessoncounts_lessondiscussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacourses',
            name='teacherPoints',
            field=models.FloatField(default=1),
        ),
    ]
