# Generated by Django 4.1 on 2022-08-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_qacourses_teacherpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qacourses',
            name='teacherPoints',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teacherPoints',
            field=models.FloatField(default=1),
        ),
    ]
