# Generated by Django 4.1 on 2022-08-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_qacourses_teacherpoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacourses',
            name='showRegularPrice',
            field=models.BooleanField(default=True),
        ),
    ]
