# Generated by Django 4.1 on 2023-01-11 06:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_couponcode_expiredate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='refBalance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='refWithdraw',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='expireDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 13, 9, 1, 30, 499796)),
        ),
        migrations.CreateModel(
            name='ReferralTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isReceiving', models.BooleanField(default=True)),
                ('refMoney', models.FloatField(blank=True, default=0.5, null=True)),
                ('withdrawMoney', models.FloatField(blank=True, default=5, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('theInrollement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.inrolledcourse')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
