# Generated by Django 4.1 on 2022-08-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_qacourses_showregularprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='categoryDesc',
            field=models.TextField(default=''),
        ),
    ]
