# Generated by Django 4.1 on 2022-08-26 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_coursecategory_categorydesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncompo',
            name='theCourse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.qacourses'),
        ),
    ]
