# Generated by Django 4.1 on 2022-08-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_lessoncompo_thecourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theInrolledCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inrolledcourse')),
            ],
        ),
    ]
