# Generated by Django 4.1 on 2022-08-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_paymentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondiscussion',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
