# Generated by Django 4.1 on 2022-09-01 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_lessondiscussion_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansText', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('theDiscussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lessondiscussion')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
