# Generated by Django 4.1 on 2022-09-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_lessonanswers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theText', models.TextField(default='')),
                ('theRate', models.IntegerField(default=3)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('theCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.qacourses')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
