# Generated by Django 4.1 on 2022-09-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_coursereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonanswers',
            name='likedTheAnswer',
            field=models.ManyToManyField(blank=True, null=True, related_name='likedUsers', to='api.userprofile'),
        ),
    ]
