# Generated by Django 4.1 on 2022-09-08 19:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_lessonanswers_likedtheanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonanswers',
            name='ansText',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
