# Generated by Django 4.1 on 2022-09-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_lessonanswers_anstext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='lessonNum',
        ),
    ]
