# Generated by Django 4.1 on 2022-09-28 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_userprofile_user_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateName', models.CharField(max_length=255)),
                ('certificateDesc', models.CharField(max_length=2655)),
                ('certificateDate', models.DateField()),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
