# Generated by Django 4.1 on 2022-10-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_instructorcertification'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='lessonNum',
            field=models.IntegerField(default=1),
        ),
    ]
