# Generated by Django 4.1 on 2022-10-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_lessons_lessonnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_activated',
            field=models.BooleanField(default=True),
        ),
    ]
