# Generated by Django 4.1 on 2022-10-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_votemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemodel',
            name='waqtiga',
            field=models.CharField(default='', max_length=255),
        ),
    ]
