# Generated by Django 4.1 on 2022-11-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_votemodel_waqtiga'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referralCode',
            field=models.CharField(default='qReff_9002', max_length=10),
        ),
    ]
