# Generated by Django 4.1 on 2022-12-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_userprofile_referralcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacourses',
            name='slag',
            field=models.CharField(default='', max_length=2555),
        ),
    ]
