# Generated by Django 4.1 on 2022-12-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_qacourses_slag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qacourses',
            old_name='slag',
            new_name='slug',
        ),
    ]
