# Generated by Django 4.1 on 2022-12-07 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_slag_qacourses_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncompo',
            name='lessonsCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lessoncompo',
            name='simDesc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lessoncompo',
            name='totalHours',
            field=models.CharField(default='30:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='lessoncompo',
            name='theCourse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theComponents', to='api.qacourses'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='compo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theCompoLessons', to='api.lessoncompo'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='theCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theLessons', to='api.qacourses'),
        ),
    ]
