# Generated by Django 4.1 on 2022-12-07 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_lessoncompo_ordernum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoncompo',
            options={'ordering': ['orderNum']},
        ),
    ]
