# Generated by Django 4.1 on 2022-12-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_lessoncompo_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qacourses',
            old_name='searchKey',
            new_name='searchKeys',
        ),
    ]
