# Generated by Django 4.1 on 2022-12-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_searchkey_qacourses_searchkeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inrolledcourse',
            name='dateInrolled',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inrolledcourse',
            name='startDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='instructorcertification',
            name='theUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theCertifications', to='api.userprofile'),
        ),
    ]
