# Generated by Django 4.1 on 2022-12-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_inrolledcourse_dateinrolled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inrolledcourse',
            name='dateInrolled',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inrolledcourse',
            name='startDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
