# Generated by Django 4.1 on 2022-12-13 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_inrolledcourse_dateinrolled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponCode', models.CharField(default='', max_length=255)),
                ('expireDate', models.DateField(default=datetime.datetime(2022, 12, 15, 19, 8, 24, 119853))),
                ('discountPrice', models.FloatField(default=5)),
            ],
        ),
    ]
