# Generated by Django 4.1 on 2022-12-18 04:39

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_couponcode_expiredate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotifications',
            options={'ordering': ['seen']},
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='expireDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 7, 39, 56, 13426)),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theNotifications', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aboutMe',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
