# Generated by Django 4.1 on 2022-12-19 04:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_usernotifications_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='expireDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 21, 7, 59, 4, 364324)),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='theCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theReviews', to='api.qacourses'),
        ),
        migrations.AlterField(
            model_name='qacourses',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='api.userprofile'),
        ),
    ]
