# Generated by Django 4.1 on 2022-12-19 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_couponcode_expiredate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='expireDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 21, 8, 0, 3, 699845)),
        ),
    ]
