# Generated by Django 4.1 on 2022-12-21 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_userprofile_username_alter_couponcode_expiredate'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacourses',
            name='hasCertificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qacourses',
            name='language',
            field=models.CharField(default='Somali', max_length=255),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='expireDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 11, 15, 1, 761290)),
        ),
    ]
