# Generated by Django 4.1 on 2022-12-25 15:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_qacourses_hascertificate_qacourses_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacourses',
            name='discountPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='qacourses',
            name='showDiscountPrice',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='expireDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 27, 18, 5, 35, 155827)),
        ),
        migrations.AlterField(
            model_name='lessonanswers',
            name='theDiscussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theDiscussionAnswers', to='api.lessondiscussion'),
        ),
        migrations.AlterField(
            model_name='lessondiscussion',
            name='theLesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theDiscussions', to='api.lessons'),
        ),
    ]
