# Generated by Django 4.1 on 2022-12-26 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_qacourses_discountprice_qacourses_showdiscountprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='expireDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 10, 50, 4, 762281)),
        ),
    ]
