# Generated by Django 4.1 on 2022-12-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutQaamuusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroImage', models.ImageField(blank=True, null=True, upload_to='images/aboutQaamuus')),
                ('heroTitle', models.CharField(max_length=255)),
                ('authHeroImage', models.ImageField(blank=True, null=True, upload_to='images/aboutQaamuus')),
                ('heroAuthTitle', models.CharField(max_length=255)),
                ('heroDesc', models.CharField(max_length=255)),
                ('heroAuthDesc', models.CharField(max_length=255)),
                ('aboutQaamuusVideo', models.FileField(upload_to='video/videoUploaded')),
                ('aboutQaamuusImage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OurInterFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/ourIntFriends')),
                ('itsActive', models.BooleanField(default=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
