# Generated by Django 4.1 on 2022-08-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourinterfriends',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
