# Generated by Django 4.1 on 2022-08-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_system', '0002_ourinterfriends_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutQaamuusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroImage', models.ImageField(blank=True, null=True, upload_to='images/aboutQaamuus')),
                ('heroTitle', models.CharField(max_length=255)),
                ('heroAuthTitle', models.CharField(max_length=255)),
                ('heroDesc', models.CharField(max_length=255)),
                ('heroAuthDesc', models.CharField(max_length=255)),
                ('aboutQaamuusVideo', models.FileField(upload_to='video/videoUploaded')),
                ('aboutQaamuusImage', models.CharField(max_length=255)),
            ],
        ),
    ]
