# Generated by Django 4.1 on 2022-12-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_system', '0005_votemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteModel',
        ),
    ]
