# Generated by Django 4.1 on 2022-12-27 12:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_alter_couponcode_expiredate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(default='', max_length=2555)),
                ('simDesc', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('dataRegistred', models.DateTimeField(auto_now=True)),
                ('prevVideo', models.CharField(max_length=2000)),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to='images/events')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/events')),
                ('videoUrl', models.CharField(default='https://qcdn.qaamuus.academy/media/video/videoUploaded/Akaadeemiyadda_Qaamuus.mp4', max_length=50000)),
                ('isLiveSdk', models.BooleanField(default=False)),
                ('isLiveIcon', models.BooleanField(default=False)),
                ('isEnded', models.BooleanField(default=False)),
                ('eventType', models.CharField(max_length=255)),
                ('dateTimeStarting', models.DateTimeField()),
                ('language', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('meetingId', models.CharField(blank=True, max_length=255)),
                ('join_URL', models.CharField(blank=True, max_length=555)),
                ('duration', models.CharField(max_length=255)),
                ('itsFree', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0)),
                ('discountPrice', models.FloatField(default=0)),
                ('showDiscountPrice', models.BooleanField(default=False)),
                ('isPublic', models.BooleanField(default=True)),
                ('heroEvent', models.BooleanField(default=False)),
                ('coHosts', models.ManyToManyField(related_name='coHosts', to='api.userprofile')),
                ('persenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persenter', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LiveEventComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField(blank=True, null=True)),
                ('dateTr', models.DateTimeField(auto_now=True)),
                ('theEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_webinar.eventview')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theText', models.TextField(default='')),
                ('theRate', models.IntegerField(default=3)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('theEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theReviews', to='a_webinar.eventview')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EventEnrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paided', models.BooleanField(default=True)),
                ('paymentMethod', models.CharField(blank=True, max_length=25, null=True)),
                ('dateTr', models.DateTimeField(auto_now=True)),
                ('theEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_webinar.eventview')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
