# Generated by Django 4.1 on 2022-08-27 18:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0019_paymentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('simDesc', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('dataRegistred', models.DateTimeField(auto_now=True)),
                ('prevVideo', models.CharField(max_length=2000)),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to='events')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events')),
                ('videoUrl', models.FileField(upload_to='videoUploaded')),
                ('eventType', models.CharField(max_length=255)),
                ('dateTimeStarting', models.DateTimeField()),
                ('language', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('itsFree', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0)),
                ('heroEvent', models.BooleanField(default=False)),
                ('isLive', models.BooleanField(default=False)),
                ('enrolledStudents', models.ManyToManyField(related_name='members', to='api.userprofile')),
                ('persenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
