# Generated by Django 4.1 on 2022-08-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_webinar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventview',
            name='isLandscape',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventview',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/events'),
        ),
        migrations.AlterField(
            model_name='eventview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/events'),
        ),
        migrations.AlterField(
            model_name='eventview',
            name='videoUrl',
            field=models.FileField(upload_to='webinar/videoUploaded'),
        ),
    ]
