# Generated by Django 4.1 on 2022-08-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_webinar', '0002_eventview_islandscape_alter_eventview_coverimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventview',
            name='videoUrl',
            field=models.FileField(blank=True, null=True, upload_to='webinar/videoUploaded'),
        ),
    ]
