# Generated by Django 4.1 on 2022-08-29 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_paymentreport'),
        ('a_webinar', '0003_alter_eventview_videourl'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEnrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paided', models.BooleanField(default=True)),
                ('paymentMethod', models.CharField(blank=True, max_length=25, null=True)),
                ('dateTr', models.DateTimeField(auto_now=True)),
                ('theEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_webinar.eventview')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
