# Generated by Django 4.1 on 2022-08-31 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_lessondiscussion_date'),
        ('a_webinar', '0004_eventenrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveEventComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField(blank=True, null=True)),
                ('dateTr', models.DateTimeField(auto_now=True)),
                ('theEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_webinar.eventview')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
