# Generated by Django 4.1 on 2022-09-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_webinar', '0005_liveeventcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventview',
            name='videoUrl',
            field=models.CharField(default='https://qcdn.qaamuus.academy/media/video/videoUploaded/Akaadeemiyadda_Qaamuus.mp4', max_length=50000),
        ),
    ]
