# Generated by Django 4.1 on 2022-10-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_webinar', '0008_eventview_isended'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventview',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
