# Generated by Django 4.1 on 2022-12-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_webinar', '0009_eventview_ispublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventview',
            name='slag',
            field=models.CharField(default='', max_length=2555),
        ),
    ]
