# Generated by Django 4.1 on 2022-12-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_webinar', '0010_eventview_slag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventview',
            old_name='slag',
            new_name='slug',
        ),
    ]
