# Generated by Django 4.1 on 2022-12-19 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_couponcode_expiredate'),
        ('a_webinar', '0011_rename_slag_eventview_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventview',
            old_name='meetingNumber',
            new_name='meetingId',
        ),
        migrations.RemoveField(
            model_name='eventview',
            name='enrolledStudents',
        ),
        migrations.RemoveField(
            model_name='eventview',
            name='meetingPassword',
        ),
        migrations.AddField(
            model_name='eventview',
            name='coHosts',
            field=models.ManyToManyField(related_name='coHosts', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='eventview',
            name='persenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persenter', to='api.userprofile'),
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theText', models.TextField(default='')),
                ('theRate', models.IntegerField(default=3)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('theEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theReviews', to='a_webinar.eventview')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
