# Generated by Django 4.1 on 2022-12-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_webinar', '0012_rename_meetingnumber_eventview_meetingid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventview',
            name='discountPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='eventview',
            name='showDiscountPrice',
            field=models.FloatField(default=0),
        ),
    ]
