# Generated by Django 4.1 on 2022-12-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_webinar', '0013_eventview_discountprice_eventview_showdiscountprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventview',
            old_name='isRealLiveSdk',
            new_name='isLiveSdk',
        ),
    ]
