# Generated by Django 4.1 on 2022-12-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_webinar', '0014_rename_isreallivesdk_eventview_islivesdk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventview',
            name='showDiscountPrice',
            field=models.BooleanField(default=False),
        ),
    ]
